pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
        PYTHON = 'C:\\Users\\vikto\\AppData\\Local\\Programs\\Python\\Python312\\python.exe'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[url: 'https://github.com/Blaha05/practice']]
                ])
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t my-fastapi-app .'
            }
        }

        stage('Run Tests in Docker') {
            steps {
                bat 'docker run --rm my-fastapi-app pytest --disable-warnings'
            }
        }

        stage('Deploy/Run') {
            steps {
                bat 'docker run -d -p 8000:8000 --name fastapi_app my-fastapi-app'
            }
        }
    }

    post {
        always {
            bat 'docker stop fastapi_app || exit 0'
            bat 'docker rm fastapi_app || exit 0'
        }
    }
}
