pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Install dependencies') {
            steps {
                sh 'python3 -m venv $VENV_DIR'
                sh './$VENV_DIR/bin/pip install --upgrade pip'
                sh './$VENV_DIR/bin/pip install -r requirements.txt'
            }
        }

        stage('Run tests') {
            steps {
                // якщо хочеш генерувати JUnit звіти — додай параметр:
                // sh './$VENV_DIR/bin/pytest --junitxml=test-results.xml'
                sh './$VENV_DIR/bin/pytest'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t fastapi-app .'
            }
        }
    }

    post {
        always {
            // закоментовано, бо test-results.xml не створюється без параметра в pytest
            // junit 'test-results.xml'
        }
    }
}
